#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import helloworld_pb2 as helloworld__pb2


class GreeterStub(object):
  """interface de serviço
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AdicionarContato = channel.unary_unary(
        '/Greeter/AdicionarContato',
        request_serializer=helloworld__pb2.Contato.SerializeToString,
        response_deserializer=helloworld__pb2.Boleano.FromString,
        )
    self.RemoverContato = channel.unary_unary(
        '/Greeter/RemoverContato',
        request_serializer=helloworld__pb2.Contato.SerializeToString,
        response_deserializer=helloworld__pb2.Boleano.FromString,
        )
    self.ListarContatos = channel.unary_stream(
        '/Greeter/ListarContatos',
        request_serializer=helloworld__pb2.Request.SerializeToString,
        response_deserializer=helloworld__pb2.Contato.FromString,
        )


class GreeterServicer(object):
  """interface de serviço
  """

  def AdicionarContato(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoverContato(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListarContatos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AdicionarContato': grpc.unary_unary_rpc_method_handler(
          servicer.AdicionarContato,
          request_deserializer=helloworld__pb2.Contato.FromString,
          response_serializer=helloworld__pb2.Boleano.SerializeToString,
      ),
      'RemoverContato': grpc.unary_unary_rpc_method_handler(
          servicer.RemoverContato,
          request_deserializer=helloworld__pb2.Contato.FromString,
          response_serializer=helloworld__pb2.Boleano.SerializeToString,
      ),
      'ListarContatos': grpc.unary_stream_rpc_method_handler(
          servicer.ListarContatos,
          request_deserializer=helloworld__pb2.Request.FromString,
          response_serializer=helloworld__pb2.Contato.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
